version: '3.7'

services:
  app:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/app
    tty: true
    networks:
      - backend
networks:
  backend:
    external: true # Use the pre-defined network `backend` : docker network create backend